{ created_at: 'Mon Oct 15 23:57:35 +0000 2018',
  id: 1051985468861149200,
  id_str: '1051985468861149184',
  text: '@razin68 is a fine lad! Love yourself please. You deserve better. Don\'t sweat it. You need to stop dragging yourself down. I believe in you.',
  source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: 109399725,
  in_reply_to_user_id_str: '109399725',
  in_reply_to_screen_name: 'razin68',
  user:
   { id: 109399725,
     id_str: '109399725',
     name: 'razin ahmed',
     screen_name: 'razin68',
     location: null,
     url: null,
     description: null,
     translator_type: 'none',
     protected: false,
     verified: false,
     followers_count: 5,
     friends_count: 29,
     listed_count: 0,
     favourites_count: 121,
     statuses_count: 182,
     created_at: 'Thu Jan 28 23:00:37 +0000 2010',
     utc_offset: null,
     time_zone: null,
     geo_enabled: false,
     lang: 'en',
     contributors_enabled: false,
     is_translator: false,
     profile_background_color: 'C0DEED',
     profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
     profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
     profile_background_tile: false,
     profile_link_color: '1DA1F2',
     profile_sidebar_border_color: 'C0DEED',
     profile_sidebar_fill_color: 'DDEEF6',
     profile_text_color: '333333',
     profile_use_background_image: true,
     profile_image_url: 'http://pbs.twimg.com/profile_images/1000556130391724032/RTSS5dzL_normal.jpg',
     profile_image_url_https: 'https://pbs.twimg.com/profile_images/1000556130391724032/RTSS5dzL_normal.jpg',
     profile_banner_url: 'https://pbs.twimg.com/profile_banners/109399725/1355269019',
     default_profile: true,
     default_profile_image: false,
     following: null,
     follow_request_sent: null,
     notifications: null },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  quote_count: 0,
  reply_count: 0,
  retweet_count: 0,
  favorite_count: 0,
  entities:
   { hashtags: [],
     urls: [],
     user_mentions: [ [Object] ],
     symbols: [] },
  favorited: false,
  retweeted: false,
  filter_level: 'low',
  lang: 'en',
  timestamp_ms: '1539647855378' }
{ created_at: 'Mon Oct 15 23:58:26 +0000 2018',
  id: 1051985682149896200,
  id_str: '1051985682149896192',
  text: '@razin68 yo stfu dweeb',
  display_text_range: [ 9, 22 ],
  source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
  truncated: false,
  in_reply_to_status_id: 1051985468861149200,
  in_reply_to_status_id_str: '1051985468861149184',
  in_reply_to_user_id: 109399725,
  in_reply_to_user_id_str: '109399725',
  in_reply_to_screen_name: 'razin68',
  user:
   { id: 1047161814713360400,
     id_str: '1047161814713360386',
     name: 'ZHBot',
     screen_name: 'FreshestMemeBot',
     location: null,
     url: null,
     description: null,
     translator_type: 'none',
     protected: false,
     verified: false,
     followers_count: 1,
     friends_count: 0,
     listed_count: 0,
     favourites_count: 0,
     statuses_count: 6,
     created_at: 'Tue Oct 02 16:30:06 +0000 2018',
     utc_offset: null,
     time_zone: null,
     geo_enabled: false,
     lang: 'en',
     contributors_enabled: false,
     is_translator: false,
     profile_background_color: 'F5F8FA',
     profile_background_image_url: '',
     profile_background_image_url_https: '',
     profile_background_tile: false,
     profile_link_color: '1DA1F2',
     profile_sidebar_border_color: 'C0DEED',
     profile_sidebar_fill_color: 'DDEEF6',
     profile_text_color: '333333',
     profile_use_background_image: true,
     profile_image_url: 'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
     profile_image_url_https: 'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
     default_profile: true,
     default_profile_image: false,
     following: null,
     follow_request_sent: null,
     notifications: null },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  quote_count: 0,
  reply_count: 0,
  retweet_count: 0,
  favorite_count: 0,
  entities:
   { hashtags: [],
     urls: [],
     user_mentions: [ [Object] ],
     symbols: [] },
  favorited: false,
  retweeted: false,
  filter_level: 'low',
  lang: 'en',
  timestamp_ms: '1539647906230' }